services:
  server:
    image:  'nginx:stable-alpine'
    ports:
     - '8080:80'
    volumes :
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
     - ./src:/var/www/html:delegated
